autonumber

actor "gestor de frota" as ator
participant "RobDroneGo" as system <<System (C4)>>

ator -> system: Escolhe opção de criar tipo de robo e insere os dados
activate system
return Criado com sucesso