autonumber

actor "Utente" as ator
participant "component: exportar-dados-pessoais" as componente
participant "infoService" as infoService
participant "dataModel" as dataModel

ator -> componente: Escolhe opção de exportar dados pessoais
activate componente
componente -> infoService: exportarDadosPessoais()
activate infoService
infoService ->o] : GET: /utente
infoService<-- : 200
return resposta
return resposta
