autonumber

participant MDRoboISEP as sistema <<Container (C4)>>
participant SGBD as sgdb <<Container>>

[o-> sistema: criar piso e insere a informação (edifício, nPiso, descricao)
activate sistema
sistema	-> sgdb: findByDomain(codigo)
activate sgdb
return edificio
sistema	-> sgdb: save(edificio)
activate sgdb
return sucesso
sistema	-> sgdb: save(piso)
activate sgdb
return sucesso
alt
<-- sistema: Ok
else "Erro"
<-- sistema: Erro
end alt


 