autonumber

participant "route: \n ElevadorRoute" as route
participant "dto: \n ElevadorDTO" as dto
participant "controller: \n ElevadorController" as ctrl
participant "service: \n ElevadorService" as service
participant "repo: \n EdificioRepo" as edRepo
participant "domain: \n Edificio" as edificio
participant "repo: \n ElevadorRepo" as eleRepo
participant "domain: \n Elevador" as elevador
participant "repo: \n PontoRepo" as PontoRepo
participant "domain: \n Piso" as Piso
participant "domain: \n Ponto" as Ponto


[o-> route: POST(json)
activate route
route -> dto ** : create(json)
route -> ctrl: editarElevador(req, res, next)
activate ctrl
ctrl -> service: editarElevador(elevadorDTO) 
activate service
service -> edRepo: findByDomain(idEdificio)
activate edRepo
return edificio
service -> edificio: returnElevador()
activate edificio
return elevador

service -> edificio : posicaoValidaNoMapa(posicao)
activate edificio
return boolean

service -> edificio: reverterMapa(listaPisos)
activate edificio
deactivate edificio

loop para cada piso
service -> Piso : pontosParaElevador(x,y,orientacao)
activate Piso
return listaPontos
end loop

loop para cada ponto
service -> Ponto : toElevador()
activate Ponto
deactivate Ponto

end loop 

service -> elevador: atualizarPisos()
activate elevador
deactivate elevador

service -> elevador: atualizarPontos()
activate elevador
deactivate elevador

service -> elevador: atualizarMarca()
activate elevador
deactivate elevador

service -> elevador: atualizarModelo()
activate elevador
deactivate elevador

service -> elevador: atualizarNumeroSerie()
activate elevador
deactivate elevador

service -> elevador: atualizarDescricao()
activate elevador
deactivate elevador

loop para cada ponto
service -> PontoRepo : save(ponto)
activate PontoRepo
deactivate PontoRepo
end loop 

service -> eleRepo: save(elevador)
activate eleRepo
deactivate eleRepo

return resposta
return resposta
return reposta













