autonumber

actor "Gestor de tarefas" as act 
participant "SistemaRobDroneGo" as sistema <<System (C4)>>

act -> sistema:  Manda um pedido para o MDtarefas com o algoritmo que deseja usar
activate sistema
return resposta

 