autonumber

actor "Gestor de campus" as actor 
participant "SistemaRobDroneGo" as sistema <<System (C4)>>

actor -> sistema: seleciona os edifícios e pede a lista de passagens
activate sistema
return resposta

 