autonumber

actor "Gestor de campus" 
participant "SistemaRobDroneGo" as sistema <<System (C4)>>

"Gestor de campus" -> sistema: seleciona o edifício e introduz pisos servidos, \nmarca, modelo, numero de série e descrição
activate sistema
return resposta

 