autonumber

actor "Gestor de campus" as ator
participant "listar-piso" as component
participant "serviceInfo" as serviceInfo
participant "dataModel" as dataModel


ator -> component: escolhe a opção editar Piso
activate component
component -> serviceInfo: listarCodEdificios()
activate serviceInfo
serviceInfo ->o] : GET listarEdificios()
serviceInfo<-- : resposta
return listaCodigos
ator <-- component: lista de codigos de edificios
ator -> component: escolhe o edificio e introduz o numero piso e descrição

component -> serviceInfo: listarPisos(codigo)
activate serviceInfo
serviceInfo ->o] : GET listarTodosOsPisosDeUmEdificio()
serviceInfo<-- : resposta
return listaPisos
ator <-- component: lista de pisos
return resposta


 