autonumber

participant RouteEdificio as route
participant "dto: EdificioDTO" as dto
participant "controller: EdificioController" as ctrl
participant "service: EdificioService" as service
participant "repository: EdificioRepo" as edRepo
participant "Edificio" as ed

[o-> route: POST(json)
activate route
route -> dto ** : create(json)
route -> ctrl: criarEdificio(edificioDTO)
activate ctrl
ctrl -> service: criarEdificio(edificioDTO) 
activate service
service -> edRepo: findByDomainId(codigo)
activate edRepo
return null
service -> ed** : create()
service -> edRepo: save(edificio)
activate edRepo
deactivate edRepo
return ok
return ok













