autonumber

participant Frontend as fe <<Container (C4)>>
participant MDRoboISEP as md <<Container (C4)>>

[o-> fe: recebe informação de criação (edificio, pisosServidos, marca, modelo, numeroSerie, descricao)
activate fe
fe	-> md: criarElevador(json)
activate md
return resposta
return resposta


 
 