autonumber

actor "Gestor de Campus" as ator
participant RobDroneGo as sistema <<System (C4)>>


ator -> sistema: quer editar a informação do piso e insere a informação para atualizar
activate sistema
return resposta


 