autonumber

participant "route: \n passagemRoute" as route
participant "controller: \n passagemController" as ctrl
participant "service: \n passagemService" as service
participant "repo: \n passagemRepo" as passRepo
participant "dto: \n passagemMapper" as mapper
participant "dto: \n passagemDTO" as dto

[o-> route: GET()
activate route
route -> dto : create(json)
activate dto
deactivate dto
route -> ctrl: listarPassagensDosEdificios(passagemDTO)
activate ctrl
ctrl -> service: listarPassagensDosEdificios(passagemDTO) 
activate service
service -> passRepo: findByEdificios()
activate passRepo
return listaDispositivos
service -> mapper : toDTO(passagem)
activate mapper
mapper -> dto : create()
activate dto
deactivate dto
return passagemDTO
return listaPassagensDTO
return listaPassagemDTO
return listaPassagemDTO













