@startuml
left to right direction
actor "Ator" as ator
actor "Gestor de Frota" as frota
usecase "Criar Edificio" as UC150
usecase "Editar Edifício" as UC160
usecase "Listar todos os Edifícios" as UC170
usecase "Listar Edifícios com min e max de pisos" as UC180
usecase "Criar Piso de um Edificio" as UC190
usecase "Editar Piso" as UC200
usecase "Listar todos os Pisos de um Edificio" as UC210
usecase "Listar Pisos de Edifício com passagens para outros edifícios"  as UC220
usecase "Carregar Mapa de Piso" as UC230
usecase "Criar Passagem entre Edifícios" as UC240
usecase "Editar passagem entre ediifícios" as UC250
usecase "Listar passagens entre 2 edifícios" as UC260
usecase "Criar Elevador de um Edifício" as UC270
usecase "Editar Elevador de um Edifício" as UC280
usecase "Listar Elevadores de um Edifício" as UC290
usecase "Listar pisos de edifícios servidos por elevador" as UC300
usecase "Criar Sala de um Piso" as UC310

usecase "Adicionar novo tipo de robot" as UC350
usecase "Adicionar novo robot à frota" as UC360
usecase "Inibir um robot" as UC370
usecase "Consultar todos os robots de forta" as UC380
usecase "Pesquisar todos os robots da frota por designação ou tarefa" as UC390

ator --> UC150
ator --> UC160
ator --> UC170
ator --> UC180
ator --> UC190
ator --> UC200
ator --> UC210
ator --> UC220
ator --> UC230
ator --> UC240
ator --> UC250
ator --> UC260
ator --> UC270
ator --> UC280
ator --> UC290
ator --> UC300
ator --> UC310

frota --> UC350
frota --> UC360
frota --> UC370
frota --> UC380
frota --> UC390

@enduml