autonumber

participant Frontend as fe <<Container (C4)>>
participant MDRoboISEP as md <<Container (C4)>>

[o-> fe: recebe informação de edição (edificio, pisosServidos, marca, modelo, numeroSerie, descricao)
activate fe
fe	-> md: editarElevador(json)
activate md
return resposta
return resposta


 
 