autonumber

participant RouteEdificio as route
participant "controller: EdificioController" as ctrl
participant "service: EdificioService" as service
participant "repository: EdificioRepo" as edRepo
participant "mapper: EdificioMapper" as mapper
participant "dto: EdificioDTO" as dto

[o-> route: GET()
activate route
route -> ctrl: listarEdificios()
activate ctrl
ctrl -> service: listarEdificios()
activate service
service -> edRepo: getAllEdificios()
activate edRepo
return listaEdificios
service -> mapper : toDTO(edificio)
activate mapper
mapper -> dto ** : edificio
return edificioDTO

return listaEdificios
return listaEdificios













