global using Xunit;
global using Moq;
global using MDTarefas.Services.IServices;
global using MDTarefas.Services;
global using MDTarefas.repos.IRepos; 
global using MDTarefas.repos; 
global using MDTarefas.dto; 
global using MDTarefas.Models.exceptions;
global using MDTarefas.Models.tarefa;